[package]
name = "agent_lib"
version = "0.1.0"
edition = "2021"

[dependencies]
embedded-hal = "0.2.7"
toml = "0.5"
thiserror = "1.0.37"
chrono = { version = "0.4.23", features = ["serde"] }
anyhow.workspace = true
serde = { workspace = true, features = ["derive"] }