[package]
name = "agent_lib"
version = "0.1.0"
edition = "2021"

[dependencies]
toml = "0.5"
serde = { version = "1.0.91", features = ["derive"] }
rppal = "0.13.1"
thiserror = "1.0.37"
chrono = { version = "0.4.23", features = ["serde"] }
anyhow = "1.0.68"