[package]
name = "agent"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
agent_lib = { path ="../agent_lib" }
lib = { path ="../lib" }
async-std = "1.12.0"
anyhow = "1.0.68"